### ISSUE TITLE
Unable to build the 1.19 jar 

### ISSUE THREAD

**Issue by Thrumptus** [gbl/StatsSearch#3]
I'm trying to build the jar in the cloned repository using gradle but im getting this error,
* What went wrong:
Could not compile settings file 'C:\Users\anon\StatsSearch\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  Apologies if this is a basic mistake, i'm still unfamiliar with this stuff

**Comment by gbl** [comment]
Complains about the class file version normally mean you're using an older version of java. Make sure you're java version is 17.

**Comment by Thrumptus** [comment]
So far as i can tell i've had it installed for a while, would this be it? 
![image](https://user-images.githubusercontent.com/93964920/183916480-8587e4c1-c5eb-4da6-bced-00102388e793.png)
Unless i need it somewhere else
